apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pvol
  labels:
     app: wordpress
     vol: mysql
     type: nfs
spec:
     capacity:
       storage: 1Gi
     accessModes:
       - ReadWriteMany
     persistentVolumeReclaimPolicy: Retain
     nfs:
       server: 10.0.1.5       
       path: /root/mysql_data
       readOnly: false
