apiVersion: v1
kind: PersistentVolume
metadata:
  name: word-pvol
  labels:
     vol: word
     app: wordpress
     type: nfs
spec:
     capacity:
       storage: 1Gi
     accessModes:
       - ReadWriteMany
     persistentVolumeReclaimPolicy: Retain
     nfs:
       server: 10.0.1.5       
       path: /root/wordpress_data
       readOnly: false
