apiVersion: v1
kind: Service
metadata:
  name: word-svc
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: frontend
  type: NodePort 
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 32001  
