apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pvol-nfs
  labels:
     type: nfs
spec:
     capacity:
       storage: 1Gi
     accessModes:
       - ReadWriteMany
     persistentVolumeReclaimPolicy: Retain
     nfs:
       server: 10.0.1.5       
       path: /root/jenkins
       readOnly: false
