apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
  - port: 5000
    name: random
    targetPort: 5000
    nodePort: 30002
    protocol: TCP
