apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: jenkins
    spec:
        containers:
        - name: jenkins
          image: jenkins
          volumeMounts:
          - mountPath: /var/jenkins_home/
            name: jenkins-pvol
          ports:
          - name: http
            containerPort: 9090
          - name: random
            containerPort: 5000
        volumes:
        - name: jenkins-pvol
          persistentVolumeClaim:
                  claimName: jenkins-claim
