apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pvol
  labels:
     type: local
spec:
     capacity:
       storage: 1Gi
     accessModes:
       - ReadWriteOnce
     persistentVolumeReclaimPolicy: Recycle
     storageClassName: local-storage
     local:
       path: /root/jenkins_data
     nodeAffinity:
         required:
           nodeSelectorTerms:
           - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - ubuntu-kubernetes 
