apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
  ports:
  - port: 3306
    name:  mysql-internal-svc
