apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-deploy
  labels:
    app: wordpress
spec:
  selector:
   matchLabels:
     app: wordpress
     tier: frontend
  strategy:
    type: Recreate
  replicas: 2 
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
        containers:
        - name: wordpress
          image: wordpress:4.8-apache
          volumeMounts:
          - mountPath: /var/www/html
            name: word-pvol
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
          - name: WORDPRESS_DB_HOST 
            value: mysql-svc
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          ports:
          - name: http
            containerPort: 80
        volumes:
           - name: word-pvol
             persistentVolumeClaim:
                  claimName: word-claim
